---
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: nestjs
      context: .
      docker:
        cacheFrom:
          - node:14-slim
        target: dev-source
      sync:
        manual:
          - src: '*.json'
            dest: '/app'

          - src: 'src/**/**'
            dest: '/app'
  local:
    useBuildkit: true

profiles:
  - name: debug
    activation:
      - command: debug
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: debug-source

  - name: debug-brk
    activation:
      - command: debug-brk
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: debug-source-brk

  - name: test
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: test
