---

apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
    - image: registry.local:5000/nestjs
      context: .
      docker:
        cacheFrom:
          - node:12-slim
        target: dev
      sync:
        manual:
          - src: '*.json'
            dest: '/app'

          - src: 'src/**/**'
            dest: '/app'
  tagPolicy:
    gitCommit:
