apiVersion: skaffold/v2beta9
kind: Config

build:
  artifacts:
    - image: nestjs
      context: .
      sync:
        manual:
          - src: src/**
            dest: /app
      docker:
        target: prod
        cacheFrom:
          - node:14
          - gcr.io/distroless/nodejs:14

  local:
    useBuildkit: true

profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: dev-source

  - name: debug
    activation:
      - command: debug
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: debug-source

  - name: debug-brk
    activation:
      - command: debug-brk
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: debug-source-brk

  - name: test
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: test
