---

apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: nestjs
      context: .
      docker:
        cacheFrom:
          - node:14-slim
        target: dev-source
      sync:
        manual:
          - src: '*.json'
            dest: '/app'

          - src: 'src/**/**'
            dest: '/app'
  local:
    useBuildkit: true
