apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  ports:
    - port: 3000
  type: LoadBalancer
  selector:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: nestjs
          command: ['npm']
          args: ['run', 'start:dev']
          env:
            - name: POSTGRES_HOST
              value: nestjs-postgres
            - name: POSTGRES_DB
              value: nestjs-database
            - name: POSTGRES_USER
              value: nestjs-user
            - name: POSTGRES_PASSWORD
              value: nestjs-password
          ports:
            - containerPort: 3000
