---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: localhost:32000/nestjs
          command: ['npm']
          args: ['run', 'start:dev']
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_HOST
              value: nestjs-postgres
            - name: POSTGRES_DB
              value: nestjs-database
            - name: POSTGRES_USER
              value: nestjs-user
            - name: POSTGRES_PASSWORD
              value: nestjs-password
          ports:
            - containerPort: 3000
