---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - name: nestjs-app
          image: nestjs
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
